# Generated by Django 5.0.6 on 2024-06-29 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycustomuser',
            old_name='city',
            new_name='postcode',
        ),
    ]
