# Generated by Django 5.0.6 on 2024-06-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryapp', '0002_rename_city_mycustomuser_postcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bakery_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
