# Generated by Django 5.0.6 on 2024-06-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryapp', '0003_bakery_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bakery_recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('img1', models.FileField(null=True, upload_to='product_images')),
                ('name', models.CharField(max_length=60)),
                ('price', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=100)),
                ('inches', models.CharField(max_length=100)),
            ],
        ),
    ]
