# Generated by Django 5.0.6 on 2024-06-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryapp', '0004_bakery_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakery_recipe',
            name='img1',
            field=models.FileField(default=1, upload_to='product_images'),
            preserve_default=False,
        ),
    ]
