# Generated by Django 5.0.6 on 2024-06-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryapp', '0006_cart_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomuser',
            name='number_pare',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='cart_count',
        ),
    ]
