# Generated by Django 5.0.6 on 2024-07-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryapp', '0008_add_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='our_signature_creations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='our_signature_creations')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
    ]
