# Generated by Django 5.0.6 on 2024-07-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryapp', '0009_our_signature_creations'),
    ]

    operations = [
        migrations.CreateModel(
            name='our_products_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='our_products_data')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
    ]
