# Generated by Django 5.0.6 on 2024-07-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryapp', '0010_our_products_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('of', models.CharField(max_length=200)),
            ],
        ),
    ]
