# Generated by Django 5.0.6 on 2024-07-06 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryapp', '0011_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='our_signature_creations',
            name='name',
        ),
    ]
