# Generated by Django 5.0.6 on 2024-07-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryapp', '0013_rename_our_signature_creations_our_signature_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakery_category',
            name='img',
            field=models.FileField(default=1, upload_to='category'),
            preserve_default=False,
        ),
    ]
