# Generated by Django 5.0.6 on 2024-07-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakeryapp', '0014_bakery_category_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_cart',
            name='qyt',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
    ]
